backend:
  name: git-gateway
  branch: main # Branch to update

media_folder: "public/uploads" # Media files will be stored here
public_folder: "/uploads" # The src attribute for uploaded media

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Published Date", name: "published", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Category", name: "category", widget: "string", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Language", name: "lang", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }